---
name: inputparameters
on:
  workflow_dispatch:
    inputs:
      environment:
        description: this is inputparameters code
        required: true
        default: test
      owner:
        description: this owner is sri
        required: true
        default: 93926
jobs:
  inputparameter:
    runs-on: ubuntu-latest
    steps:
      - name: run input parameter
        run: echo "Deploy the application ${{inputs.environment}}"
